- name: VLAN's for layer 2 Switches
  hosts: switches
  collections:
    - cisco.ios
  tasks:
    - name: Create VLANs 10,20,99
      ios_config:
        lines:
          - vlan 10
          - name VLAN_10
          - vlan 20
          - name VLAN_20
          - vlan 30
          - name VLAN_99
